name: i am still here
favicon: null
layout_spectrum: 0.74614
typography_spectrum: 0.32349
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a2a2a2'
    - '#7d7d7d'
    - '#3f3f3f'
    - '#090909'
    - '#efefef'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
